---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels: 
    app.kubernetes.io/instance: rag-test-oct15
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: rag-test-oct15 
  name: rag-test-oct15
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 100Gi